### ISSUE TITLE
prepare_tidygenomes

### ISSUE THREAD

**Issue by rrdelahaba** [SWittouck/tidygenomes#1]
I found a bug in the "prepare_tidygenomes" function. Essentially, the "add_phylogroups" function was the problem, since the phylogroups were not properly assigned.

I could solve the problem loading the "add_phylogroups" function in the "importers.R" script into my R environment. Then, I could run the "prepare_tidygenomes" function without problems. Well, the "root" function was also giving me an error, so, I decided not to use it and instead I used a rooted tree as an input.

**Comment by SWittouck** [comment]
Hi Rafa, 

Thanks for reporting this bug!

The problem was indeed the `root_tree` function. It was treating the node/tip labels as branch labels instead of node labels. 

It should be fixed now. Could you maybe update tidygenomes and try again, to verify? 

Cheers, 
Stijn

**Comment by rrdelahaba** [comment]
Hi Stijn,

Thank you so much, after installing the updated version of tidygenomes I could root the tree, create the tidygenome object, and assign phylogroups without any problems. You can close this issue.

Cheers,

Rafa
